### PR TITLE
Add Bl.ocks.org Profiles section

### LINKED ISSUE #42: Idea: Awesome Bl.ocks.org Profiles
Has anyone compiled a list of most epic bl.ocks.org profiles? I feel like that needs to be a thing, and this would be a great place for it. Here's a start:

# Awesome Bl.ocks.org Profiles

 * https://bl.ocks.org/1wheel
 * https://bl.ocks.org/ColinEberhardt
 * https://bl.ocks.org/HarryStevens
 * https://bl.ocks.org/LuisSevillano
 * https://bl.ocks.org/d3indepth
 * https://bl.ocks.org/emeeks
 * https://bl.ocks.org/enjalot
 * https://bl.ocks.org/fil
 * https://bl.ocks.org/mbostock
 * https://bl.ocks.org/micahstubbs
 * https://bl.ocks.org/nbremer
 * https://bl.ocks.org/nitaku
 * https://bl.ocks.org/susielu
 * https://bl.ocks.org/sxywu
 * https://bl.ocks.org/syntagmatic
 * https://bl.ocks.org/tomshanley
 * https://bl.ocks.org/vasturiano
 * https://bl.ocks.org/veltman
 * https://bl.ocks.org/zanarmstrong

### PR DESCRIPTION
**Pull request by curran**
Closes #42

This is a first pass at what this section could look like. Any feedback? Formatting OK? Idea is good? Thanks!

### CODE REVIEW

**Comment by g-div** [comment]
Definitively a good idea to have such a list. But I'm not sure if it fits well here. Are there some community feedback ? Up-vote (+1) or down-vote (-1) this PR.

I also have the following concerns about formatting:
1) please use an `<h2>` title (using two hashes: `## Bl.ocks.org Profiles`) as for others sections
2) what do you think about `[Adam Pearce - wheel](https://bl.ocks.org/1wheel)` ? I think this will be more informative than a mere list of links

**Comment by curran** [comment]
@g-div Great ideas! I agree, this needs community interest, and I'm not sure if it's there.

I also agree regarding formatting. Makes perfect sense. Thank you for reviewing.

**Comment by g-div** [comment]
Ok, It starts looking interesting to me. I'll merge this.

A further improvement would be to add a short description as we did for the other entries. This could be useful to let people think a little bit longer before including certain profiles in the list, providing a kind of *natural selection* (see "How to prevent people spamming with their own boring profiles?").
It would maybe be too much for now, you've already done a great job here, but let's think/discuss about this option.

Thanks!

**Comment by curran** [comment]
Great! Thank you for merging.

Perhaps some criteria like "must have over 50 bl.ocks" and "over 90% of bl.ocks must have thumbnails".

**Pull request merged**
